### ISSUE TITLE
Problem on the client side

### ISSUE THREAD

**Issue by esteban-master** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#38]
The render of react does not work, when I enter the section "Running and opening in the browser" (Adding a React Frontend to Complete MERN), when entering the command "yarn development". 

I have all the code you wrote up to that chapter, the backend works fine. In the client it does not render the main.js template of react (cannot GET/)
Here I leave the link to the repository of the code that I have, it is the same as the one in the indicated section (https://github.com/esteban-master/esqueleto_MERN)

The course of the book is great, I can not continue reading ... I hope your help. Thank you very much!

**Comment by shamahoque** [comment]
The [server/express.js](https://github.com/esteban-master/esqueleto_MERN/blob/master/server/express.js) file in your code is missing the code from Chapter 3, section “Serving an HTML template at a root URL”:

```
import Template from './../template'
...
app.get('/', (req, res) => {
 res.status(200).send(Template())
})
...
```

This declares the / (root) route on the server. 
You are seeing the _cannot GET /_ error since the server cannot find this declaration.

**Comment by esteban-master** [comment]
Thank you very much! That's the problem I was having in my code, a newbie bug of mine. Greetings!
